name: Build & Test

on:
  pull_request:
  push:
    branches: ['**']
    # Ignore pushes on tags to prevent two uploads of codecov reports
    tags-ignore: ['**']
  workflow_dispatch:
    # Allow to run manually
    inputs:
      platform:
        description: 'Platform'
        required: true
        default: 'ubuntu-focal-standard'
      docker_tag:
        description: 'Docker tag'
        required: true
        default: 'dev'

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/sagemath/sage/sage-${{ github.event.inputs.platform || 'ubuntu-focal-standard' }}-with-targets:${{ github.event.inputs.docker_tag || 'dev'}}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Update system packages
        id: prepare
        run: |
          export PATH="build/bin:$PATH"
          eval $(sage-print-system-package-command auto update)
          eval $(sage-print-system-package-command auto --spkg --yes --no-install-recommends install git)

      - name: Add prebuilt tree as a worktree
        id: worktree
        run: |
          set -ex
          git config --global user.email "ci-sage@example.com"
          git config --global user.name "Build & Test workflow"
          git config --global --add safe.directory $(pwd)
          # If actions/checkout downloaded our source tree using the GitHub REST API
          # instead of with git (because do not have git installed in our image),
          # we first make the source tree a repo.
          if [ ! -d .git ]; then git init && git add -A && git commit -m "new"; fi
          # Tag this state of the source tree "new". This is what we want to build and test.
          git tag -f new
          # Our container image contains a source tree in /sage with a full build of Sage.
          # But /sage is not a git repository.
          # We make /sage a worktree whose index is at tag "new".
          # We then commit the current sources and set the tag "old". (This keeps all mtimes unchanged.)
          # Then we update worktree and index with "git reset --hard new".
          # (This keeps mtimes of unchanged files unchanged and mtimes of changed files newer than unchanged files.)
          # Finally we reset the index to "old". (This keeps all mtimes unchanged.)
          # The changed files now show up as uncommitted changes.
          git worktree add --detach worktree-image
          rm -rf /sage/.git && mv worktree-image/.git /sage/
          rm -rf worktree-image && ln -s /sage worktree-image
          if [ ! -f worktree-image/.gitignore ]; then cp .gitignore worktree-image/; fi
          (cd worktree-image && git add -A && git commit --allow-empty -m "old" -a && ls src/sage/misc && git tag -f old && git reset --hard new && ls src/sage/misc && git reset old && ls src/sage/misc)
