name: CI Linux

## This GitHub Actions workflow runs SAGE_ROOT/tox.ini with select environments,
## whenever a GitHub pull request is opened or synchronized in a repository
## where GitHub Actions are enabled.
##
## It builds and checks some sage spkgs as defined in TARGETS.
##
## A job succeeds if there is no error.
##
## The build is run with "make V=0", so the build logs of individual packages are suppressed.
##
## At the end, all package build logs that contain an error are printed out.
##
## After all jobs have finished (or are canceled) and a short delay,
## tar files of all logs are made available as "build artifacts".

#on: [push, pull_request]

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    # Allow to run manually

env:
  TARGETS_PRE: all-sage-local
  TARGETS: build doc-html
  TARGETS_OPTIONAL: ptest

permissions:
  packages: write

jobs:

  standard-sitepackages:
    uses: ./.github/workflows/docker.yml
    with:
      # Build incrementally from previous stage (pre)
      incremental: true
      free_disk_space: true
      from_docker_repository: ghcr.io/sagemath/sage/
      from_docker_target: "with-targets-pre"
      from_docker_tag: dev
      docker_targets: "with-targets with-targets-optional"
      # FIXME: duplicated from env.TARGETS
      targets: build doc-html
      targets_optional: ptest
      tox_packages_factors: >-
        ["standard-sitepackages"]
      # Only test systems with a usable system python (>= 3.9)
      tox_system_factors: >-
        ["ubuntu-jammy",
         "ubuntu-kinetic",
         "ubuntu-lunar",
         "ubuntu-mantic",
         "debian-bullseye",
         "debian-bookworm",
         "debian-trixie",
         "debian-sid",
         "linuxmint-21",
         "linuxmint-21.1",
         "linuxmint-21.2",
         "fedora-33",
         "fedora-34",
         "fedora-35",
         "fedora-36",
         "fedora-37",
         "fedora-38",
         "fedora-39",
         "centos-stream-8-python3.9",
         "centos-stream-9-python3.9",
         "almalinux-8-python3.9",
         "gentoo-python3.10",
         "gentoo-python3.11",
         "archlinux-latest",
         "opensuse-15.4-gcc_11-python3.10",
         "opensuse-15.5-gcc_11-python3.11",
         "opensuse-tumbleweed-python3.10",
         "opensuse-tumbleweed",
         "debian-bullseye-i386"]
      docker_push_repository: ghcr.io/${{ github.repository }}/
      max_parallel: 30
